### ISSUE TITLE
ERD

### ISSUE THREAD

**Issue by medlenmage** [nss-evening-cohort-12/nutshell-chital#14]
![clown college erd](https://user-images.githubusercontent.com/62913995/87486108-1b631780-c600-11ea-97ce-ce218925bba2.png)

Entity Relationship Diagram for the data for students, teachers, classes, and lessons.

**Comment by atphy** [comment]
![clown college](https://user-images.githubusercontent.com/39771100/87608520-c1c52080-c6c5-11ea-90e4-3c698d52703b.png)
