### ISSUE TITLE
Teachers Read

### ISSUE THREAD

**Issue by olamide87** [nss-evening-cohort-12/nutshell-chital#18]

**Comment by olamide87** [comment]
## USER STORY
As a user, when the Teachers page loads, I should see many different  Teachers cards 

## AC
WHEN the page loads, I should see teachers information displayed on the screen.
THEN  I should be able to scroll down to see more cards containing even more sectors.
AND I should be able to return to the navbar and go to the other pages.

## DEV NOTES
1.create a folder called teachers
2.create a file inside it called teachers.js
3.in the teachers.js create a domString call teacherrMaker()


1.Create a bootstrap card with an image, fields for name, occupied, and explored, and also buttons for edit and delete

2.create a click event for the Edit button with the class edit-teacher 

3.create a click event for the Delete button with the class delete-teacher

4.create a click event for the Add button with the class add-teacher

5.create a folder called Teachers

6.inside that folder create a file called Teachers.js

7.The purpose of this file to to store the buildTeacher, editTeacher, and deleteTeacher functions

8.import necessary components

9.the buildTeacher function will look like this...



1.create a file called TeacherData.js in the data folder
2.create a function called getTeachers

**Comment by michaelclark2** [comment]
what's this about sectors and cows???
